### PR TITLE
Lm updating portugal

### PR DESCRIPTION
**Pull request by LaurelMorrison**
updating the nav bar and Portugal page

### CODE REVIEW

**Review by TarynL — CHANGES_REQUESTED** [review]
Remove 1 Philippines link in nav bar of portugal html.

**Review by Coachbre — CHANGES_REQUESTED** [review]
The anchor tags and links in the "icons" class on the index.html were removed, along with the corresponding CSS that changed the hover color of the country names under each image on the home page (main.css lines 93-98 and index.html lines 37-75). Our main branch currently contains that code. I think merging your main first then creating another pull request should fix the conflicts.

**Review by abbeyroyse13 — APPROVED** [review]
Found it!

**Review by Coachbre — APPROVED** [review]
You are such a shining star

**Review by TarynL — APPROVED** [review]

**Pull request merged**
